
plugins {
    id 'org.jetbrains.kotlin.jvm' version "2.3.0"
    id 'org.jetbrains.kotlin.plugin.allopen' version "2.3.0"
    id 'io.quarkus'
}

sourceSets {
    main {
        kotlin {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['resources']
        }
    }
    test {
        kotlin {
            srcDirs = ['test']
        }
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        allWarningsAsErrors = true
    }
}

tasks.named('quarkusGenerateCodeTests') {
    doFirst {
        mkdir 'build/classes/java/main'
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-mailer'
    implementation 'io.quarkus:quarkus-mongodb-client'
    implementation 'org.mongodb:mongodb-driver-sync'
    implementation 'io.quarkus:quarkus-rest'
    implementation 'io.quarkus:quarkus-hibernate-validator'
    implementation 'org.json:json:20230227'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    implementation 'de.mkammerer:argon2-jvm:2.11'
    implementation 'org.mongodb:bson:4.11.0'

    testImplementation 'io.quarkus:quarkus-junit-mockito'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.3.1'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'io.mockk:mockk:1.13.10'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.quarkus:quarkus-test-mongodb'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

allOpen {
    annotation('jakarta.ws.rs.Path')
    annotation('jakarta.enterprise.context.ApplicationScoped')
    annotation('jakarta.persistence.Entity')
    annotation('io.quarkus.test.junit.QuarkusTest')
}

tasks.named('compileKotlin', org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
    kotlinOptions.jvmTarget = '21'
    kotlinOptions.javaParameters = true
}

tasks.named('compileTestKotlin', org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
    kotlinOptions.jvmTarget = '21'
}
