#------------------------------------------------------------------#
#                       QUARKUS CONFIGURATION                      #
#------------------------------------------------------------------#
quarkus.http.port=80
quarkus.http.host=0.0.0.0

#------------------------------------------------------------------#
#                       MONGODB CONFIGURATION                      #
#------------------------------------------------------------------#
%test.quarkus.mongodb.hosts=
%test.quarkus.mongodb.devservices.enabled=true
quarkus.mongodb.hosts=${MONGODB_HOST:localhost:27017}
quarkus.mongodb.credentials.username=${MONGODB_USERNAME:}
quarkus.mongodb.credentials.password=${MONGODB_PASSWORD:}

#------------------------------------------------------------------#
#                        SMTP CONFIGURATION                        #
#------------------------------------------------------------------#
quarkus.mailer.host=${SMTP_HOST:smtp.gmail.com}
quarkus.mailer.port=${SMTP_PORT:587}
quarkus.mailer.start-tls=${SMTP_START_TLS:REQUIRED}
quarkus.mailer.username=${SMTP_USERNAME}
quarkus.mailer.password=${SMTP_PASSWORD}
quarkus.mailer.from=${SMTP_FROM}

#------------------------------------------------------------------#
#                     APPLICATION CONFIGURATION                    #
#------------------------------------------------------------------#
primary.tenant=${MICROCHESS_TENANT:microchess}
google.tenant=${GOOGLE_TENANT:google}
google.api.url=${GOOGLE_API_URL:https://www.googleapis.com/oauth2/v2/userinfo}